import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useQuery } from '@apollo/client'
import { usePostsQuery } from 'generated'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const { data, error, loading } = usePostsQuery();
  //to define the types of data : post query type is used
  if(loading) return (
    <main className={styles.main}>
      Loading..
    </main>
  );
  if(error) return (
    <main className={styles.main}>
      {error.message}
    </main>
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{data?.posts?.data[0].attributes?.Title}</h1>
      </main>
    </>
  )
}
